// <auto-generated />
using System;
using EscolaAtenta.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaAtenta.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.AlertaEvasao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloudSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataAlerta")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataResolucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JustificativaResolucao")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservacaoResolucao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolvido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ResolvidoPorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("TurmaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataAlerta")
                        .HasDatabaseName("IX_AlertasEvasao_DataAlerta");

                    b.HasIndex("ResolvidoPorId");

                    b.HasIndex("AlunoId", "Resolvido");

                    b.HasIndex("Resolvido", "DataResolucao");

                    b.HasIndex("TurmaId", "Resolvido");

                    b.HasIndex("Resolvido", "DataResolucao", "Tipo")
                        .HasDatabaseName("IX_AlertasEvasao_Auditoria");

                    b.HasIndex("Resolvido", "Tipo", "Nivel");

                    b.ToTable("AlertasEvasao", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("AtrasosNoTrimestre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CloudSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataExclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioTrimestre")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaltasConsecutivasAtuais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("FaltasNoTrimestre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFaltas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioExclusao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Chamada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloudSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId", "DataHora");

                    b.ToTable("Chamadas", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revogado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.RegistroPresenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChamadaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloudSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ChamadaId", "AlunoId")
                        .IsUnique();

                    b.ToTable("RegistrosPresenca", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TabelaOrigem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeId");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("SyncLogs", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("CloudSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataExclusao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioExclusao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("CloudSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataExclusao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeveAlterarSenha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscolaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Papel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioExclusao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Ativo] = 1");

                    b.HasIndex("Email", "Ativo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.AlertaEvasao", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Aluno", "Aluno")
                        .WithMany("AlertasEvasao")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscolaAtenta.Domain.Entities.Usuario", "ResolvidoPor")
                        .WithMany()
                        .HasForeignKey("ResolvidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EscolaAtenta.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.Navigation("Aluno");

                    b.Navigation("ResolvidoPor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Chamada", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Turma", "Turma")
                        .WithMany("Chamadas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.RegistroPresenca", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Aluno", "Aluno")
                        .WithMany("RegistrosPresenca")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscolaAtenta.Domain.Entities.Chamada", "Chamada")
                        .WithMany("RegistrosPresenca")
                        .HasForeignKey("ChamadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Chamada");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("AlertasEvasao");

                    b.Navigation("RegistrosPresenca");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Chamada", b =>
                {
                    b.Navigation("RegistrosPresenca");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Chamadas");
                });
#pragma warning restore 612, 618
        }
    }
}
