// <auto-generated />
using System;
using EscolaAtenta.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EscolaAtenta.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.AlertaEvasao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataAlerta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Resolvido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("AlertasEvasao", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Chamada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Chamadas", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.RegistroPresenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChamadaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ChamadaId", "AlunoId")
                        .IsUnique();

                    b.ToTable("RegistrosPresenca", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.AlertaEvasao", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Aluno", "Aluno")
                        .WithMany("AlertasEvasao")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Chamada", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Turma", "Turma")
                        .WithMany("Chamadas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.RegistroPresenca", b =>
                {
                    b.HasOne("EscolaAtenta.Domain.Entities.Aluno", "Aluno")
                        .WithMany("RegistrosPresenca")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EscolaAtenta.Domain.Entities.Chamada", "Chamada")
                        .WithMany("RegistrosPresenca")
                        .HasForeignKey("ChamadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Chamada");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("AlertasEvasao");

                    b.Navigation("RegistrosPresenca");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Chamada", b =>
                {
                    b.Navigation("RegistrosPresenca");
                });

            modelBuilder.Entity("EscolaAtenta.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Chamadas");
                });
#pragma warning restore 612, 618
        }
    }
}
