using EscolaAtenta.Infrastructure.Services;
using EscolaAtenta.Domain.Entities;
using EscolaAtenta.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EscolaAtenta.Infrastructure.Data;

/// <summary>
/// Serviço responsável por popular dados críticos iniciais no banco de dados.
/// Chamado durante o startup da API.
/// </summary>
public class DatabaseSeeder
{
    private readonly AppDbContext _context;
    private readonly ILogger<DatabaseSeeder> _logger;

    public DatabaseSeeder(AppDbContext context, ILogger<DatabaseSeeder> logger)
    {
        _context = context;
        _logger = logger;
    }

    /// <summary>
    /// Roda as lógicas de seed pendentes.
    /// </summary>
    public async Task SeedAsync()
    {
        await SeedConfiguracaoEscolaAsync();
        await SeedHistoricoMatriculasAsync();
        await SeedAdminAsync();
    }

    private async Task SeedConfiguracaoEscolaAsync()
    {
        bool existeConfiguracao = await _context.ConfiguracoesEscola.AnyAsync();
        if (existeConfiguracao)
            return;

        _logger.LogInformation("Nenhuma configuração da escola encontrada. Criando configuração padrão (Trimestre)...");

        var configuracao = new ConfiguracaoEscola(Guid.NewGuid(), TipoPeriodoLetivo.Trimestre);
        _context.ConfiguracoesEscola.Add(configuracao);
        await _context.SaveChangesAsync();
    }

    private async Task SeedHistoricoMatriculasAsync()
    {
        // Alunos criados antes da existência do histórico de matrículas precisam
        // receber uma matrícula ativa retroalimentada com base na turma atual.
        var alunosSemHistorico = await _context.Alunos
            .AsNoTracking()
            .Where(a => !_context.AlunosTurmasHistorico.Any(h => h.AlunoId == a.Id))
            .Select(a => new { a.Id, a.TurmaId })
            .ToListAsync();

        if (alunosSemHistorico.Count == 0)
            return;

        _logger.LogInformation(
            "Retroalimentando histórico de matrículas para {Quantidade} aluno(s) sem histórico...",
            alunosSemHistorico.Count);

        var turmas = await _context.Turmas
            .AsNoTracking()
            .Where(t => alunosSemHistorico.Select(a => a.TurmaId).Contains(t.Id))
            .ToDictionaryAsync(t => t.Id, t => t.AnoLetivo);

        foreach (var aluno in alunosSemHistorico)
        {
            if (!turmas.TryGetValue(aluno.TurmaId, out var anoLetivo))
                continue;

            // Data de início retroalimentada como o primeiro dia do ano letivo
            var dataInicio = new DateTime(anoLetivo, 1, 1, 0, 0, 0, DateTimeKind.Utc);

            var historico = new AlunoTurmaHistorico(
                Guid.NewGuid(),
                aluno.Id,
                aluno.TurmaId,
                anoLetivo,
                dataInicio,
                dataFim: null,
                "Retroalimentação automática");

            _context.AlunosTurmasHistorico.Add(historico);
        }

        await _context.SaveChangesAsync();
    }

    private async Task SeedAdminAsync()
    {
        // Verifica se já existe algum administrador no sistema
        bool hasAdmin = await _context.Usuarios.AnyAsync(u => u.Papel == PapelUsuario.Administrador);

        if (!hasAdmin)
        {
            _logger.LogInformation("Nenhum Administrador encontrado no sistema. Iniciando provisionamento...");

            string adminNome = "Administrador do Sistema";
            string adminEmail = "admin@escolaatenta.com.br";
            string autoGeneratedPassword = PasswordGenerator.Generate(14);

            // AppSec: Utilizamos o BCrypt para gerar o hash localmente antes de salvar
            string hashSenha = BCrypt.Net.BCrypt.HashPassword(autoGeneratedPassword);

            var adminUser = new Usuario(adminNome, adminEmail, hashSenha, PapelUsuario.Administrador);
            adminUser.ExigirTrocaDeSenha(); // Senha auto-gerada: forcar troca no primeiro login

            _context.Usuarios.Add(adminUser);
            await _context.SaveChangesAsync();
            
            _logger.LogWarning("==================================================================================");
            _logger.LogWarning("[SECURITY] USUÁRIO ADMINISTRADOR CRIADO COM SUCESSO!");
            _logger.LogWarning("Email: {Email}", adminEmail);
            _logger.LogWarning("Senha: {Senha}", autoGeneratedPassword);
            _logger.LogWarning("ATENÇÃO: Anote esta senha imediatamente. Ela não será exibida novamente.");
            _logger.LogWarning("==================================================================================");
        }
    }
}
