using EscolaAtenta.Infrastructure.Services;
using EscolaAtenta.Domain.Entities;
using EscolaAtenta.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EscolaAtenta.Infrastructure.Data;

/// <summary>
/// Serviço responsável por popular dados críticos iniciais no banco de dados.
/// Chamado durante o startup da API.
/// </summary>
public class DatabaseSeeder
{
    private readonly AppDbContext _context;
    private readonly ILogger<DatabaseSeeder> _logger;

    public DatabaseSeeder(AppDbContext context, ILogger<DatabaseSeeder> logger)
    {
        _context = context;
        _logger = logger;
    }

    /// <summary>
    /// Roda as lógicas de seed pendentes.
    /// </summary>
    public async Task SeedAsync()
    {
        await SeedAdminAsync();
    }

    private async Task SeedAdminAsync()
    {
        // Verifica se já existe algum administrador no sistema
        bool hasAdmin = await _context.Usuarios.AnyAsync(u => u.Papel == PapelUsuario.Administrador);

        if (!hasAdmin)
        {
            _logger.LogInformation("Nenhum Administrador encontrado no sistema. Iniciando provisionamento...");

            string adminNome = "Administrador do Sistema";
            string adminEmail = "admin@escolaatenta.com.br";
            string autoGeneratedPassword = PasswordGenerator.Generate(14);

            // AppSec: Utilizamos o BCrypt para gerar o hash localmente antes de salvar
            string hashSenha = BCrypt.Net.BCrypt.HashPassword(autoGeneratedPassword);

            var adminUser = new Usuario(adminNome, adminEmail, hashSenha, PapelUsuario.Administrador);
            adminUser.ExigirTrocaDeSenha(); // Senha auto-gerada: forcar troca no primeiro login

            _context.Usuarios.Add(adminUser);
            await _context.SaveChangesAsync();
            
            _logger.LogWarning("==================================================================================");
            _logger.LogWarning("[SECURITY] USUÁRIO ADMINISTRADOR CRIADO COM SUCESSO!");
            _logger.LogWarning("Email: {Email}", adminEmail);
            _logger.LogWarning("Senha: {Senha}", autoGeneratedPassword);
            _logger.LogWarning("ATENÇÃO: Anote esta senha imediatamente. Ela não será exibida novamente.");
            _logger.LogWarning("==================================================================================");
        }
    }
}
